name: Lint
on:
  push:
    branches:
      - '**'
      - '!production'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Build content before linting for typesafety
        run: pnpm build

      - name: Lint
        run: pnpm lint
        env:
          SKIP_VALIDATION: true

      - name: Typecheck
        run: pnpm typecheck
